cups: add missing cups/ppd.h include
Fix compile-time errors when building rastertoaps with cups-2.2.4:

- options.c:187:9: error: unknown type name 'ppd_file_t'
- options.c:197:15: warning: implicit declaration of function
  'ppdOpenFile' [-Wimplicit-function-declaration]

Forwarded: techsupport@aps-printers.com
Signed-off-by: Roland Hieber <r.hieber@pengutronix.de>